BROWSER= chrome
HEADLESS=false
ENV=dev
BASE_URL=https://eventhub.rahulshettyacademy.com/login
EXPLICIT_WAIT_TIMEOUT= 10
HARD_WAIT_TIMEOUT= 2
STEP_TIME= 0
PAGE_LOAD_TIMEOUT= 60
SCREENSHOT_PATH= ./exports/screenshots/
RECORD_VIDEO_PATH= ./exports/videos/
RECORD_VIDEO=yes
SCREENSHOT_STEP_ALL=no
EXTENT_REPORT_PATH=exports/ExtentReport/ExtentReport.html
AUTHOR=Injas Mahendra Berutu
LOCATE=en



VALID_LOGIN_EMAIL=tests@mail.com
VALID_LOGIN_PASSWORD=Test@123