BROWSER= chrome
HEADLESS=false

EXPLICIT_WAIT_TIMEOUT= 10
HARD_WAIT_TIMEOUT= 2
STEP_TIME= 1
PAGE_LOAD_TIMEOUT= 60
SCREENSHOT_PATH= ./exports/screenshots/
RECORD_VIDEO_PATH= ./exports/videos/
RECORD_VIDEO=yes
SCREENSHOT_STEP_ALL=no
EXTENT_REPORT_PATH=exports/ExtentReport/ExtentReport.html
AUTHOR=Injas Mahendra Berutu
LOCATE=en