BROWSER= chrome
HEADLESS=false
ENV=dev
USER_NAME= Mahendra
EMAIL= mahendra_test@mail.com
PASSWORD= Mahendra@27
EXPLICIT_WAIT_TIMEOUT= 10
HARD_WAIT_TIMEOUT= 2
STEP_TIME= 0
PAGE_LOAD_TIMEOUT= 60
SCREENSHOT_PATH= ./exports/screenshots/
RECORD_VIDEO_PATH= ./exports/videos/
RECORD_VIDEO=yes
SCREENSHOT_STEP_FAIL=yes
SCREENSHOT_STEP_PASS=no
SCREENSHOT_STEP=no
EXTENT_REPORT_PATH=reports/ExtentReport.html
AUTHOR=Injas Mahendra Berutu
LOCATE=en