# Cart
CART_PAGE=//a[contains(text(),'Cart')]
CART_FOOTER=#footer
CART_SUBSCRIPTION_LABEL=//h2[contains(text(),'Subscription')]
INPUT_SUBSCRIBE_EMAIL=//input[@id='susbscribe_email']
CART_SUBSCRIBE_BUTTON=//button[@id='subscribe']
SUCCESS_ALERT_MESSAGE=//div[@class='alert-success alert']
CART_TABLE_DATA=//table/tbody/tr
VERIFY_SHOPPING_CART_PAGE=.active
PROCEED_TO_CHECKOUT=//a[normalize-space(text())='Proceed To Checkout']
VERIFY_CHECKOUT_POP_UP=//h4[@class='modal-title w-100']
REGISTER_OR_LOGIN=//u[normalize-space(text())='Register / Login']
VERIFY_ADDRESS_DETAIL=//h2[@class='heading'])[1]
VERIFY_REVIEW_YOUR_ORDER=(//h2[@class='heading'])[2]
TYPE_COMMENT_BEFORE_CHECKOUT=//textarea[@class='form-control']
PLACE_ORDER_BUTTON=.btn.btn-default.check_out
DELETE_PRODUCT_BUTTON=.cart_quantity_delete
CART_PRODUCT_NOW=//table[@id='cart_info_table']//tbody/tr

# Checkout
DELIVERY_ADDRESS=//ul[@id='address_delivery']

# Contact Us
CONTACT_US_BUTTON=//a[normalize-space()='Contact us']
GET_IN_TOUCH_LABEL=//h2[contains(text(),'Get In Touch')]
CUSTOMER_NAME=//div[@class='form-group col-md-6']//input[@type='text']
CUSTOMER_EMAIL=//div[@class='form-group col-md-6']//input[@type='email']
CUSTOMER_SUBJECT=//div[@class='form-group col-md-12']//input[@type='text']
CUSTOMER_MESSAGE=#message
BROWSE_FILE_BUTTON=//input[@type='file']
SUBMIT_BUTTON=//input[@type='submit']
SUCCESSFUL_MESSAGE=//div[@class='status alert alert-success']
HOME_BUTTON=//span[contains(text(),'Home')]
LANDING_PAGE_CONTACT_US_IMG=//img[@src='/static/images/home/logo.png']

# Home
LANDING_PAGE_HOME_IMG=//img[@src='/static/images/home/logo.png']
HOME_FOOTER=footer
CONTACT_US_SUBSCRIPTION_LABEL=div[class='single-widget'] h2
SUBSCRIBE_EMAIL=//input[@id='susbscribe_email']
HOME_SUBSCRIBE_BUTTON=//button[@id='subscribe']
SUCCESS_MESSAGE_LABEL=//div[@class='alert-success alert']
CATEGORY_LABEL=//h2[contains(text(),'Category')]
CATEGORY_BY=//div[@class='panel-group category-products']/div//h4/a
WOMEN_CATEGORY_EXTEND=(//i[@class='fa fa-plus'])[1]
WOMEN_CATEGORY_EXTEND_2=(//a[@data-parent='#accordian']//span)[1]
MEN_CATEGORY_EXTEND=(//i[@class='fa fa-plus'])[2]
MEN_CATEGORY_EXTEND_2=(//span[@class='badge pull-right']//i)[2]
KIDS_CATEGORY_EXTEND=(//i[@class='fa fa-plus'])[3]
KIDS_CATEGORY_EXTEND_2=(//span[@class='badge pull-right']//i)[3]
CLICKED_CATEGORY_PAGE_LABEL=.title.text-center
RECOMMENDED_ITEMS_IS_VISIBLE=//h2[normalize-space(text())='recommended items']
ADD_TO_CART_BUTTON=(//div[@class='recommended_items']//a[contains(text(), 'Add to cart')])[1]
VIEW_CART=//u[contains(text(),'View Cart')]
CLICK_SCROLL_UP_BUTTON=//a[@id='scrollUp']
SCROLL_UP_LABEL=//div[@class='item active']//div[@class='col-sm-6']//h2[contains(text(),'Full-Fledged practice website for Automation Engin')]

# Login & Register
GO_TO_LOGIN_BUTTON=//a[contains(text(),'Signup / Login')]
HOME_PAGE=//img[@alt='Website for automation practice']
REGISTER_LABEL=div[class='signup-form'] h2
NEW_USER_SIGN_UP=//*[contains(text(),'New User Signup!')]
SIGN_UP_BUTTON=//button[contains(text(),'Signup')]
USER_NAME=//form[@action='/signup']/input[@placeholder='Name']
USER_EMAIL_ADDRESS=//form[@action='/signup']//input[@type='email']
ACCOUNT_INFORMATION_LABEL=//b[contains(text(),'Enter Account Information')]
CREATE_ACCOUNT_BUTTON=//button[contains(text(),'Create Account')]
Mr_GENDER=id_gender1
Mrs_GENDER=id_gender2
USER_PASSWORD=//input[@id='password']
DAYS=//select[@id='days']
MONTHS=//select[@id='months']
YEARS=//select[@id='years']
CHECKBOX_SIGN_UP=#newsletter
CHECKBOX_RECEIVE_SPECIAL_OFFERS=#optin
USER_FIRST_NAME=//input[@id='first_name']
USER_LAST_NAME=#last_name
USER_COMPANY=#company
USER_ADDRESS1=#address1
USER_ADDRESS2=#address2
USER_COUNTRY=//select[@id='country']
USER_STATE=//input[@id='state']
USER_CITY=//input[@id='city']
USER_ZIPCODE=//input[@id='zipcode']
USER_MOBILE_NUMBER=#mobile_number
ACCOUNT_CREATED_LABEL=//b[contains(text(),'Account Created!')]
CONTINUE_BUTTON=//a[@class='btn btn-primary']
DELETE_BUTTON=//a[contains(text(),'Delete Account')]
LOGIN_LABEL=//h2[contains(text(),'Login to your account')]
CREATED_USER_EMAIL=//form[@action='/login']//input[@type='email']
CREATED_USER_PASSWORD=//input[@type='password']
LOGIN_BUTTON=//button[contains(text(),'Login')]
IN_LINE_ERROR_MESSAGE=//p[@style='color: red;']
SIGN_UP_IN_LINE_ERROR_MESSAGE =//p[normalize-space()='Email Address already exist!']
LOG_OUT_BUTTON=//a[contains(text(),'Logout')]
DELETE_ACCOUNT_BUTTON=//a[normalize-space(text())='Delete Account']
ACCOUNT_DELETED_LABEL=//b[normalize-space(text())='Account Deleted!']

# Test Cases
GO_TO_TEST_CASE_BUTTON=//a[normalize-space()='Test Cases']
TEST_CASE_LABEL=//b[normalize-space()='Test Cases']

# Payment
NAME_ON_CARD=//input[@data-qa='name-on-card']
CARD_NUMBER=//input[@data-qa='card-number']
CVC=//input[@data-qa='cvc']
EXPIRY_MONTH=//input[@data-qa='expiry-month']
EXPIRY_YEAR=//input[@data-qa='expiry-year']
PAY_AND_CONFIRM_BUTTON=//button[@data-qa='pay-button']
VERIFY_ORDER_PLACED_LABEL=div[class='col-sm-9 col-sm-offset-1'] p
CONTINUE_AFTER_SUCCESS_ORDER_BUTTON=.btn.btn-primary
DOWNLOAD_INVOICE_BUTTON=.btn.btn-default.check_out

# Products
LANDING_PAGE_IMAGE=//img[@src='/static/images/home/logo.png']
PRODUCT_BUTTON=//a[contains(text(),'Products')]
ALL_PRODUCTS_PAGE=//h2[@class='title text-center']
PRODUCT_LIST=.col-sm-4
PRODUCT_INFORMATION=//div[@class='product-information']
PRODUCT_NAME_TO_SEARCH=//input[@id='search_product']
PRODUCT_SEARCH_BUTTON=#submit_search
SEARCHED_PRODUCT_LABEL=.title.text-center
VERIFY_SEARCHED_PRODUCT_IS_VISIBLE=//div[@class='productinfo text-center']/p
CONTINUE_SHOPPING_BUTTON=//button[contains(@class,'btn btn-success')]
ADD_QUANTITY=quantity
ADD_PRODUCT_TO_CART_BUTTON=//button[@type='button']
VIEW_CART_1=//u[contains(text(),'View Cart')]
VIEW_CART_2=//p[@class='text-center']//u[1]
BRAND_LABEL=//h2[normalize-space(text())='Brands']
BRAND_PRODUCT=//div[@class='brands-name']//li
BRAND_PAGE_AND_PRODUCT_IS_VISIBLE=//h2[@class='title text-center']
BRAND_AND_PRODUCT_LIST_PAGE=.features_items .col-sm-4
WRITE_YOUR_REVIEW_LABEL_IS_VISIBLE=//a[normalize-space(text())='Write Your Review']
REVIEWER_NAME_1=//input[@placeholder='Your Name']
REVIEWER_NAME_2=//form[@id='review-form']//input[1]
REVIEWER_EMAIL_1=//input[@placeholder='Email Address']
REVIEWER_EMAIL_2=(//form[@id='review-form']//input)[2]
ADD_REVIEW_1=//textarea[@placeholder='Add Review Here!']
ADD_REVIEW_2=//form[@id='review-form']//textarea[1]
SUBMIT_REVIEW_BUTTON_1=//button[normalize-space(text())='Submit']
SUBMIT_REVIEW_BUTTON_2=//form[@id='review-form']//button[1]
REVIEW_SUCCESS_MESSAGE=//span[normalize-space(text())='Thank you for your review.']