# Login Page
LOGIN_PAGE_LABEL = //h1[normalize-space()='Sign in to EventHub']
EMAIL = //input[@id='email']
PASSWORD = //input[@id='password']
SIGN_IN_BUTTON = //button[@id='login-btn']
SUCCESS_LOGIN_LABEL = //span[@id='user-email-display']
LOG_OUT_BUTTON = //button[@id='logout-btn']
ERROR_TOAST_MESSAGE = //p[@class='text-sm font-medium flex-1 leading-snug']


# Register Page
NAVIGATE_TO_REGISTER_PAGE = //a[normalize-space()='Register']
REGISTER_PAGE_LABEL = //h1[normalize-space()='Create your account']
REGISTER_EMAIL = //input[@id='register-email']
REGISTER_PASSWORD = //input[@id='register-password']
REGISTER_CONF_PASSWORD = //input[@placeholder='Repeat your password']
CREATE_ACCOUNT_BUTTON = //button[@id='register-btn']

# Event Page
NAVIGATE_TO_EVENT_PAGE = //a[@id='nav-events']


