# Login Page
LOGIN_PAGE_LABEL = //h1[normalize-space()='Sign in to EventHub']
EMAIL = //input[@id='email']
PASSWORD = //input[@id='password']
SIGN_IN_BUTTON = //button[@id='login-btn']
SUCCESS_LOGIN_LABEL = //span[@id='user-email-display']
LOG_OUT_BUTTON = //button[@id='logout-btn']
ERROR_TOAST_MESSAGE = (//p[@class='text-sm font-medium flex-1 leading-snug'])[1]

# Register Page
NAVIGATE_TO_REGISTER_PAGE = //a[normalize-space()='Register']
REGISTER_PAGE_LABEL = //h1[normalize-space()='Create your account']
REGISTER_EMAIL = //input[@id='register-email']
REGISTER_PASSWORD = //input[@id='register-password']
REGISTER_CONF_PASSWORD = //input[@placeholder='Repeat your password']
CREATE_ACCOUNT_BUTTON = //button[@id='register-btn']

# Event Page
NAVIGATE_TO_EVENT_PAGE = //a[@id='nav-events']
EVENT_PAGE_LABEL = //h1[normalize-space()='Upcoming Events']
EVENT_LIST = article#event-card
SEARCH_EVENT_INPUT = //input[@placeholder='Search events, venues…']
SELECT_EVENT_CATEGORY = body > main:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > select:nth-child(1)
SELECT_EVENT_CITY = body > main:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(3) > select:nth-child(1)
CLEAR_FILTER = //button[normalize-space()='Clear filters']
ADD_NEW_EVENT = //button[normalize-space()='Add New Event']
EVENTS = body > main:nth-child(2) > div:nth-child(1) > div:nth-child(3)
CONFIRM_BOOKING_BUTTON = //button[@id='confirm-booking']
TOTAL_PRICE_TICKET = span[class='text-indigo-700']
ADD_EVENT_BUTTON = //button[@id='add-event-btn']
EVENT_INFORMATION_DETAIL = div[class='grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6']
ABOUT_EVENT_DETAIL = //p[@class='text-gray-600 leading-relaxed whitespace-pre-wrap']


# Booking Page


